### PR TITLE
File changes

### LINKED ISSUE #19: Remove redundant OP files and reorganize dir tree
There are duplicate files across the Go and Mie folders that do not need to be here and the current directory structure is confusing- better to merge the folders, delete any duplicates and have /GO as a sub-folder of what is currently /Mie, and rename /Mie to /OP.

### LINKED ISSUE #25: filenames to snake case
change filenames to snake-case

e.g. (SNICAR_driver.py --> snicar_driver.py)

### PR DESCRIPTION
**Pull request by jmcook1186**
reorganized directory structure and rename files to snake case

Mie and Go folders no longer have redundant duplicate files

All OPs now stored in /OP_data
All LAPs now stored in OP_data/480band/laps
GO files now stored in OP_data/480band/Go
Mie files now stored in OP_data/480band/Mie
fsds files now stored in OP_data/480band/fsds
refractive indices for water, ice, etc stored in OP_Data/
pigment files in Data/pigments
miscellaneous files stored in Data/additional_data

Closes #25
Closes #19

### CODE REVIEW

**Comment by lcvl41** [comment]
- pigment data are spread between folders and should be merged. In particular, "./Data/pigments", "./Data/pigments/pigments_trials" should be merged and pigment files in and "./Data/additional_data" should also be moved to "./Data/pigments" then duplicate files deleted. also, following files should be deleted: InVivoPhenolData.csv, phenols_invivo_corrected.csv, phenol_mac_correction.csv, phenols_original.csv, phenols_invivo_corrected.csv, ppg_shifted.csv, ppg_raw_extract_mean.csv, 
ppg_raw_extract_all_stations.csv. 
- maybe the bubble_reff_calculator could be moved to a subfolder as it's not a main file
- the update_netCDFs also could go somewhere else than the main folder 
- in "./Data/OP_data/480band/GO" the files GA_HE2a, GA_only_stations, GA_Halbach2021, SA_Halbach_2021, Glacier_Algae_IS should be deleted
- suggest to rename "Mie" to "ice grains" and "GO" to "ice crystals" in ".Data/OP_data/480band" to be consistent with "bubbly_ice_files" (itself could be renamed to "bubble_inclusions" or simply "bubbly_ice" - alternatively to keep consistency put the bubbly ice folder in "Mie" but I think we should not organise following the algo used to produce the data, it's less user friendly

**Comment by jmcook1186** [comment]
Thanks!
ok, agree with pigment data organization - was hoping you would advise on which files are still relevant.
Will address all comments in next set of commits.
Prefer "hexagonal columns" and "spherical grains" to "ice grains" and "ice crystals" for renaming Mie and Go though.

**Comment by lcvl41** [comment]
> Thanks! ok, agree with pigment data organization - was hoping you would advise on which files are still relevant. Will address all comments in next set of commits. Prefer "hexagonal columns" and "spherical grains" to "ice grains" and "ice crystals" for renaming Mie and Go though.

cool! can we do "ice_hexagonal_columns" and "ice_spherical_grains"? I just think ice should appear somewhere

**Comment by jmcook1186** [comment]
ok - that should address all your comments apart from moving the r-eff calculator and netcdf builder - can we leave them where they are for now?

**Comment by lcvl41** [comment]
> ok - that should address all your comments apart from moving the r-eff calculator and netcdf builder - can we leave them where they are for now?

sure!

**Pull request merged**
